### ISSUE TITLE
CSS высота строки в Firefox

### ISSUE THREAD

**Issue by stungnthumz** [stungnthumz/shBrush1C#1]
При изменении размера шрифта блока подсветки, например:

``` css
.syntaxhighlighter.lang1c {
    font-size: 10pt !important;
}
```

В Firefoxf уменьшается высота строки (см слово "Результат" на разных строках) и появляется вертикальный скроллбар:
![firefox](https://cloud.githubusercontent.com/assets/10281912/5736141/3b1cfb4c-9be3-11e4-90f9-5a4788d731fc.png)

В IE все отображается корректно:
![ie](https://cloud.githubusercontent.com/assets/10281912/5736147/53cfcf52-9be3-11e4-81f1-d2af68179103.png)
